# Generated by Django 2.1.5 on 2019-01-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('group_size', models.IntegerField()),
                ('users', models.CharField(blank=True, default='', max_length=5000)),
                ('creator', models.CharField(max_length=150)),
                ('userson', models.CharField(blank=True, default='', max_length=5000)),
                ('di', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='di', to='project.Graph')),
                ('undi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='undi', to='project.Graph')),
            ],
        ),
    ]
