# Generated by Django 2.1.5 on 2019-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedEventId', models.TextField(max_length=50)),
                ('users', models.CharField(max_length=5000)),
            ],
        ),
    ]
